# Generated by Django 4.2.27 on 2026-01-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', verbose_name='图片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='拍摄地点')),
                ('date_taken', models.DateField(blank=True, null=True, verbose_name='拍摄日期')),
                ('camera', models.CharField(blank=True, max_length=50, verbose_name='相机')),
                ('lens', models.CharField(blank=True, max_length=50, verbose_name='镜头')),
                ('focal_length', models.CharField(blank=True, max_length=20, verbose_name='焦距')),
                ('aperture', models.CharField(blank=True, max_length=10, verbose_name='光圈')),
                ('shutter_speed', models.CharField(blank=True, max_length=20, verbose_name='快门速度')),
                ('iso', models.CharField(blank=True, max_length=10, verbose_name='ISO')),
                ('exif_data', models.JSONField(blank=True, null=True, verbose_name='完整EXIF数据')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='相册名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('theme_color', models.CharField(choices=[('#3C4856', '鸦青'), ('#B78B5D', '琥珀'), ('#2A5CAA', '黛蓝'), ('#D03B40', '朱砂')], default='#3C4856', max_length=7, verbose_name='主题色')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精选')),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_cover', to='gallery.photo', verbose_name='封面照片')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.photoalbum', verbose_name='相册'),
        ),
    ]
